version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      global_network:
        aliases:
          - redis_bd_global
      bd_network:
        aliases:
          - redis_bd
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-data:/data/db
    ports:
      - "1888:27017"
    networks:
      global_network:
        aliases:
          - mongo_bd_global
      bd_network:
        aliases:
          - mongo_bd
  api:
    build: .
    ports:
      - "3000:3000"
    networks:
      global_network:
        aliases:
          - api_global
      api_network:
        aliases:
          - api
    depends_on:
      - mongo
  proxy:
    tty: true
    build: 
      context: ./
      dockerfile: ./proxy/Dockerfile
    ports:
      - "443:443"
    networks:
      global_network:
        aliases:
          - proxy_global
      api_network:
        aliases:
          - proxy
    depends_on:
      - mongo

networks:
  global_network:
    name: global_net
    driver: bridge
    ipam:
      driver: default
  bd_network:
    name: bd_net
    driver: bridge
    ipam:
      driver: default
  api_network:
    name: api_net
    driver: bridge
    ipam:
      driver: default

volumes:
  mongo-data: